### ISSUE TITLE
Enhancement: DatadogMetricsConfigurer expansions should be configurable

### ISSUE THREAD

**Issue by morrowgi** [aol/micro-server#270] opened 2016-10-18 20:39 UTC
In DatadogMetricsConfigurer the following means all metrics are pushed to datadog daemon:

`EnumSet<DatadogReporter.Expansion> expansions = EnumSet.of(ALL);`

This should be configurable via spring or otherwise

**Comment by johnmcclean-aol** [comment] 2016-10-21 13:41
Duplicate of this one -> https://github.com/aol/micro-server/issues/258

**Comment by johnmcclean-aol** [comment] 2016-11-06 23:18
Merged

**Closed by johnmcclean-aol** 2016-11-06 23:18 UTC
Labels: enhancement
